[package]
name = "renard"
version = "0.1.0"
authors = ["Julian Pokrovsky <juliankul@gmail.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.3.0"
trace = { git = "https://github.com/gsingh93/trace", branch = "master" }
